project_name: terraform-provider-lago

before:
  hooks:
    - go mod tidy

builds:
  - id: terraform-provider-lago
    binary: terraform-provider-lago
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "terraform-provider-lago_{{ .Version }}_SHA256SUMS"

changelog:
  use: git
